name: Yarn CI

on: [push]

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - name: yarn install
        run: yarn

      - name: yarn lint
        run: yarn lint
